import type { ExamQuestion } from "@/types/exam";

export const sampleQuestions: ExamQuestion[] = [
  {
    id: "ups-basic-001",
    certificationId: "hcip-dcf",
    examVersion: "HCIP-DCF mock v1",
    topic: "UPS Basic",
    subtopic: "Power conversion",
    difficulty: "foundation",
    type: "single",
    text: "Which component converts DC power into AC power in a UPS system?",
    options: [
      { id: "a", label: "A", text: "Rectifier", isCorrect: false, rationale: "The rectifier converts AC into DC." },
      { id: "b", label: "B", text: "Inverter", isCorrect: true, rationale: "The inverter converts DC into AC for the load." },
      { id: "c", label: "C", text: "Static bypass unit", isCorrect: false, rationale: "Bypass transfers load to bypass input." },
      { id: "d", label: "D", text: "Charger", isCorrect: false, rationale: "The charger replenishes battery energy." },
    ],
    explanation: "The inverter changes DC from the DC bus or batteries into AC output power.",
    sourceType: "mock_exam",
    sourceReference: "Seed HCIP-DCF sample",
  },
  {
    id: "smartli-001",
    certificationId: "hcip-dcf",
    examVersion: "HCIP-DCF mock v1",
    topic: "SmartLi",
    subtopic: "Lithium battery safety",
    difficulty: "intermediate",
    type: "multiple",
    text: "Which statements about SmartLi battery deployment are correct?",
    options: [
      { id: "a", label: "A", text: "Battery modules should be installed according to the specified polarity.", isCorrect: true, rationale: "Wrong polarity can damage equipment and create safety hazards." },
      { id: "b", label: "B", text: "Battery cabinets can be installed without checking grounding.", isCorrect: false, rationale: "Grounding is part of the required safety checks." },
      { id: "c", label: "C", text: "The battery management system monitors module status and alarms.", isCorrect: true, rationale: "SmartLi relies on monitoring for alarms, status, and protection." },
      { id: "d", label: "D", text: "Ventilation and clearance requirements can be ignored for short runtime systems.", isCorrect: false, rationale: "Clearance and environment requirements still apply." },
    ],
    explanation: "SmartLi deployment needs correct polarity, grounding, environment checks, and battery management monitoring.",
    sourceType: "mock_exam",
    sourceReference: "Seed HCIP-DCF sample",
  },
  {
    id: "cooling-001",
    certificationId: "hcip-dcf",
    examVersion: "HCIP-DCF mock v1",
    topic: "Cooling",
    subtopic: "Room cooling",
    difficulty: "foundation",
    type: "true_false",
    text: "True or False: Cooling deployment should consider airflow organization as well as equipment cooling capacity.",
    options: [
      { id: "true", label: "True", text: "True", isCorrect: true, rationale: "Airflow organization affects whether cooling capacity reaches equipment correctly." },
      { id: "false", label: "False", text: "False", isCorrect: false, rationale: "Capacity alone is not enough if airflow is poor." },
    ],
    explanation: "Data center cooling design considers capacity, hot/cold airflow, layout, and environmental requirements.",
    sourceType: "mock_exam",
    sourceReference: "Seed HCIP-DCF sample",
  },
  {
    id: "ecc800-001",
    certificationId: "hcip-dcf",
    examVersion: "HCIP-DCF mock v1",
    topic: "ECC800 / NetEco",
    subtopic: "Monitoring",
    difficulty: "intermediate",
    type: "single",
    text: "Which platform is commonly associated with centralized management and monitoring of Huawei data center infrastructure?",
    options: [
      { id: "a", label: "A", text: "NetEco", isCorrect: true, rationale: "NetEco is associated with centralized infrastructure monitoring and management." },
      { id: "b", label: "B", text: "SmartLi", isCorrect: false, rationale: "SmartLi is a lithium battery system." },
      { id: "c", label: "C", text: "UPS2000", isCorrect: false, rationale: "UPS2000 is a UPS product line." },
      { id: "d", label: "D", text: "FusionDC 1000", isCorrect: false, rationale: "FusionDC 1000 is an integrated data center solution." },
    ],
    explanation: "ECC800 and NetEco appear often around infrastructure monitoring in Huawei facility deployment material.",
    sourceType: "mock_exam",
    sourceReference: "Seed HCIP-DCF sample",
  },
  {
    id: "ups5000-001",
    certificationId: "hcip-dcf",
    examVersion: "HCIP-DCF mock v1",
    topic: "UPS5000",
    subtopic: "Deployment checks",
    difficulty: "advanced",
    type: "multiple",
    text: "Before powering on a UPS5000 system, which checks are appropriate?",
    options: [
      { id: "a", label: "A", text: "Verify cable connections and torque where required.", isCorrect: true, rationale: "Connection checks are part of safe commissioning." },
      { id: "b", label: "B", text: "Confirm input and output switches are in the expected state.", isCorrect: true, rationale: "Switch position checks help prevent incorrect energization." },
      { id: "c", label: "C", text: "Skip grounding inspection if the cabinet is fixed to the floor.", isCorrect: false, rationale: "Mechanical installation does not replace grounding inspection." },
      { id: "d", label: "D", text: "Check for foreign objects inside the cabinet.", isCorrect: true, rationale: "Foreign object inspection is a common pre-power-on safety step." },
    ],
    explanation: "UPS commissioning verifies wiring, grounding, switches, cleanliness, and safety before power-on.",
    sourceType: "mock_exam",
    sourceReference: "Seed HCIP-DCF sample",
  },
  {
    id: "fusionmodule-001",
    certificationId: "hcip-dcf",
    examVersion: "HCIP-DCF mock v1",
    topic: "FusionModule 2000",
    subtopic: "Modular data center",
    difficulty: "intermediate",
    type: "single",
    text: "FusionModule 2000 is best described as which type of solution?",
    options: [
      { id: "a", label: "A", text: "A modular data center solution", isCorrect: true, rationale: "FusionModule 2000 is positioned as a modular data center solution." },
      { id: "b", label: "B", text: "A standalone UPS battery module only", isCorrect: false, rationale: "It covers more than battery modules." },
      { id: "c", label: "C", text: "A fire extinguisher controller only", isCorrect: false, rationale: "Fire systems may be integrated, but that is not the whole solution." },
      { id: "d", label: "D", text: "A handheld commissioning terminal", isCorrect: false, rationale: "It is infrastructure, not a handheld terminal." },
    ],
    explanation: "FusionModule 2000 brings together power, cooling, monitoring, cabinets, cabling, and other modular data center elements.",
    sourceType: "mock_exam",
    sourceReference: "Seed HCIP-DCF sample",
  },
];
